### ISSUE TITLE
 Can't resolve 'cordova-plugin-file-transfer' 

### ISSUE THREAD

**Issue by marcelloinfoweb** [apache/cordova-plugin-file-transfer#358] opened 2023-01-07 22:10 UTC
Install command: `npm install https://github.com/apache/cordova-plugin-file-transfer`

Command: vue-cli-service serve
![image](https://user-images.githubusercontent.com/2093128/211172027-b2304d6c-1166-4c43-b620-aec08c5b8ebe.png)

**Comment by breautek** [comment] 2023-01-09 14:38
Cordova plugins aren't really an NPM module so to speak. They are distributed through NPM, but they cannot be required or resolved as a typical NPM module. Cordova has it's own module system in which Cordova will embed the plugin's JS into your application when Cordova is loaded, clobbering the global namespace as defined in their `plugin.xml` file. It is an antiquated system, an artefact that existed before NPM even existed.

So to work around your issue, remove the `cordova-plugin-file-transfer` import in your code. Depending on your framework/build system, you may also need to prefix the API call with `window.` or configure it to accept additional global variables.

As long as the `deviceready` event has fired, any cordova plugin APIs should be available and ready to be used.

Closing as not a bug.

**Closed by breautek** 2023-01-09 14:38 UTC
