### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET set to 8.0

### ISSUE THREAD

**Issue by rolinger** [apache/cordova-plugin-file-transfer#319] opened 2021-10-18 14:38 UTC
Installing `cordova-plugin-file-downloader` installs the following plugins, in this order

cordova-plugin-file 6.0.2 "File"
cordova-plugin-file-md5 0.3.3 "MD5 Checksum"
cordova-plugin-file-transfer 1.7.1 "File Transfer"
cordova-plugin-network-information 3.0.0 "Network Information"
cordova-plugin-zip 3.1.0 "cordova-plugin-zip"
cordova-plugin-file-downloader 0.4.0 "Downloader"

During CLI build: `ionic cordova build ios` - I get the following error specifically on the `cordova-plugin-file-transfer` plugin.  

```
warning: The iOS deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 14.1.99. (in target 'GoogleSignIn' from project 'Pods')
** ARCHIVE FAILED **

The following build commands failed:
	CompileC /Users/rpo/Library/Developer/Xcode/DerivedData/MyCoolApp-cznpcyycbfuwvvdmoufvkdvbzdan/Build/Intermediates.noindex/ArchiveIntermediates/MyCoolApp/IntermediateBuildFilesPath/MyCoolApp.build/Debug-iphoneos/MyCoolApp.build/Objects-normal/arm64/CDVFileTransfer.o /Users/rpo/dev/MyCoolApp_4.0.0/platforms/ios/MyCoolApp/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

As I am certain everyone is already aware, with Cordova 10/Cordova-iOS@6.x - **the minimum deployment target supported is iOS 11.**

I backed out all 6 plugins and installed them 1 at a time (in the same order) and doing a build after each plugin install to pinpoint which one was causing the error.  After manually installing the `cordova-plugin-file-transfer` plugin, and performing the build, the same error caused the build to fail again.

I don't see anyone else reporting this error so I am hoping there is an easy fix for it.

### Version information
```
Ionic:

   Ionic CLI         : 6.17.1 (/Users/rpo/.nvm/versions/node/v14.18.1/lib/node_modules/@ionic/cli)
   Ionic Framework   : ionic1 1.3.4
   @ionic/v1-toolkit : 3.2.15

Cordova:

   Cordova CLI       : 10.0.0 (cordova-lib@10.1.0)
   Cordova Platforms : ios 6.2.0
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 5.0.0, (and 19 other plugins)

Utility:

   cordova-res : 0.15.3
   native-run  : 1.5.0

System:

   ios-deploy : 1.11.4
   ios-sim    : 8.0.2
   NodeJS     : v14.18.1 (/Users/rpo/.nvm/versions/node/v14.18.1/bin/node)
   npm        : 6.14.15
   OS         : macOS Big Sur
   Xcode      : Xcode 12.1 Build version 12A7403

```

## Checklist

- [x ] I searched for existing GitHub issues
- [x ] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by jcesarmobile** [comment] 2022-06-01 23:54
Closing since the problem is not present on the dev version

**Closed by jcesarmobile** 2022-06-01 23:54 UTC
