### ISSUE TITLE
build fail in ios

### ISSUE THREAD

**Issue by anshu300** [apache/cordova-plugin-file-transfer#265] opened 2020-08-05 13:16 UTC
he following build commands failed: /Users/RK/Documents/IONIC/ionic/wema-test/platforms/ios/wemalife-app/Plugins/cordova-plugin-file-transfer/CDVFileTransfer.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler

“@ionic-native/file-transfer”: “^5.27.0”,

“cordova-plugin-file-transfer”: “^1.7.1”,

build fail in ios

Ionic:

Ionic CLI : 5.4.16 (/usr/local/lib/node_modules/ionic) Ionic Framework : ionic-angular 3.9.2 @ionic/app-scripts : 3.2.4

Cordova:

Cordova CLI : 10.0.0 Cordova Platforms : ios 6.1.0 Cordova Plugins : cordova-plugin-ionic-keyboard 2.2.0, (and 23 other plugins)

Utility:

cordova-res : not installed native-run : not installed

System:

ios-sim : 8.0.2 NodeJS : v12.18.3 (/usr/local/bin/node) npm : 6.14.6 OS : macOS Catalina Xcode : Xcode 11.6 Build version 11E708

**Comment by timbru31** [comment] 2020-08-05 15:02
Duplicate of #258

**Closed by timbru31** 2020-08-05 15:02 UTC
