### ISSUE TITLE
ARC semantic issue

### ISSUE THREAD

**Issue by narenderreddych** [apache/cordova-plugin-file-transfer#278] opened 2020-09-09 14:06 UTC
### Issue Type

- [X] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
Upgraded the Cordova iOS platform version to 6.1.1 
While building the application got the error **"ARC Semantic issue"**- No known instance method for selector **userAgent**
I tried with CLI - The error is like 
**cordova-plugin-file-transfer/CDVFileTransfer.m normal arm64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
xcodebuild: Command failed with exit code 65**

### Environment, Platform, Device

iOS 6.1.1
Xcode 11.7
Cordova 10.0

### Version information

Xcode, Cordova: Cordova CLI, Cordova Platforms, Cordova Plugins 
![Screenshot 2020-09-09 at 7 10 45 PM](https://user-images.githubusercontent.com/7994498/92608770-65e8d380-f2d3-11ea-8144-e167b6b22711.png)

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

![Screenshot 2020-09-09 at 7 10 45 PM](https://user-images.githubusercontent.com/7994498/92608730-59fd1180-f2d3-11ea-9e95-994ce870f2a5.png)

**Comment by timbru31** [comment] 2020-09-09 14:12
Duplicate of #258

**Closed by timbru31** 2020-09-09 14:12 UTC

**Comment by pks0268** [comment] 2022-03-02 06:10
By removing lines 107-110 from CDVFileTransfer.m I was able to compile:

    NSString* userAgent = [self.commandDelegate userAgent];
    if (userAgent) {
        [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
    }

**Comment by jayasin** [comment] 2022-04-01 16:44
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
> NSString* userAgent = [self.commandDelegate userAgent];
> if (userAgent) {
>     [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
> }
> ```

Yes it's working for me, Thanks a lot

**Comment by danielehrhardt** [comment] 2022-05-06 21:45
`npm install https://github.com/apache/cordova-plugin-file-transfer.git`
