### ISSUE TITLE
userAgent method is missing in Cordova-ios 6.0.0

### ISSUE THREAD

**Issue by eyganeshv** [apache/cordova-plugin-file-transfer#264] opened 2020-08-04 08:44 UTC
# Bug Report
'userAgent' method is missing in Cordova-ios 6.0.0 and 6.1.0 version. 

### What is expected to happen?
'userAgent' method is support both cordova-ios 5.0.0 and 51.0 version.

### What does actually happen?
shows a red warning message "No known instance method for selector 'userAgent'" in applyRequestHeaders method.

## Information

At present UIWebView is no more.  WKWebview is supporting the latest version only like Cordova 6.0.0 above version. So we cant back the old Cordova-ios version. Kindly fix this issue for the same latest Cordova-ios version.
  
### Command or Code

`NSString* userAgent = [self.commandDelegate userAgent];`

### Version information
cordova-plugin-file-transfer 1.7.2-dev "File Transfer"
Cordova 9.0.0
Cordova-ios 6.0.0
XCode 11.5
Mac OS Catalina

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by timbru31** [comment] 2020-08-04 09:48
Duplicate of #258

**Closed by timbru31** 2020-08-04 09:48 UTC

**Comment by danielehrhardt** [comment] 2022-05-06 21:45
`npm install https://github.com/apache/cordova-plugin-file-transfer.git`
