### ISSUE TITLE
No known instance method for selector 'userAgent' in CDVFileTransfer.m

### ISSUE THREAD

**Issue by alssl-ross** [apache/cordova-plugin-file-transfer#258] opened 2020-06-02 19:18 UTC
# Bug Report

## Problem
When building using cordova-ios v6.0.0 an error is thrown saying:

"No known instance method for selector 'userAgent' in CDVFileTransfer.m"

### What is expected to happen?

iOS build and run without error.

### What does actually happen?

Error occurs as above

## Information
The error occurs on line 107 of CDVFileTransfer.m":

`NSString* userAgent = [self.commandDelegate userAgent];`

### Command or Code
Create a Cordova v9 project using cordova-ios 6.0.0 platform and version 1.7.1 of cordova-plugin-file-transfer
run: 
cordova build ios

### Environment, Platform, Device
Build error occurs using Cordova v9.
cordova-ios 6.0.0
cordova-file-transfer-plugin v1.7.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by kokitang** [comment] 2020-06-03 09:05
+1

**Comment by jansc** [comment] 2020-06-04 11:17
+1

**Comment by fabmesto** [comment] 2020-06-05 08:32
Same error with:
cordova-ios: 6.0.0
cordova-plugin-file-transfer : 1.7.1

**Comment by jansc** [comment] 2020-06-05 09:04
By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
```    
    NSString* userAgent = [self.commandDelegate userAgent];
    if (userAgent) {
        [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
    }
```

**Comment by kolbasa** [comment] 2020-06-05 17:52
Thank you very much, I'll try that. You can no longer publish an app with cordova-ios v5.1.1. This issue should be a top priority.

**Comment by fabmesto** [comment] 2020-06-08 10:02
is there any alternative to this plugin?

**Comment by kolbasa** [comment] 2020-06-08 11:14
https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

**Comment by alssl-ross** [comment] 2020-06-08 14:59
I did go through the process of moving from this plugin to XHR but found that it failed for downloads of large zip files, causing me to revert back to this plugin.

I can compile now thanks to @jansc's comment above. I'm wondering if there is any effect on functionality from removing the userAgent lines. I've not been able to test for myself as yet.

**Comment by vtellez** [comment] 2020-06-09 07:57
Same error with:
cordova-ios: 6.0.0
cordova-plugin-file-transfer : 1.7.1

I cant not compile with @jansc Solution because Ive got:  Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m:27:9: 'Cordova/CDVUserAgentUtil.h' file not found if I delete Lines 107-110

**Comment by kolbasa** [comment] 2020-06-09 08:04
That was fixed on the master branch of `cordova-plugin-inappbrowser`:
https://github.com/apache/cordova-plugin-inappbrowser/pull/715

**Comment by sohanpc** [comment] 2020-06-11 12:16
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

It's working for me. 
Thank you for saving my time

**Comment by alssl-ross** [comment] 2020-06-11 13:59
Given the plugin is deprecated, is it worth creating a pull request? I'm not sure if anyone is able to merge the pull request if it was created.

I've forked this repository and made this change in if it's of use to anyone:

https://github.com/alssl-ross/cordova-plugin-file-transfer

**Comment by MrJohn2014** [comment] 2020-06-16 20:59
Same issue here. I just comment lane 107-110 and my project could build successfully.

**Comment by hefler** [comment] 2020-06-19 13:32
Although @alssl-ross did a fork removing the lines, I thought about combining @kolbasa 's solution tip into an own fork: https://github.com/zoopit/cordova-plugin-file-transfer

**Comment by sc0ttdav3y** [comment] 2020-06-24 09:15
Please @alssl-ross create a PR, and hopefully someone with access can merge it in.

**Comment by HansKrywaa** [comment] 2020-07-17 06:56
I switched to use [this Fork](https://github.com/dpa99c/cordova-plugin-file-transfer)

**Comment by Lyfei** [comment] 2020-07-23 01:42
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

After deleting, my network request will not succeed. It seems that userAgent is needed

**Comment by timbru31** [comment] 2020-07-23 09:26
I've created a thread on the dev mailing list to **discuss** the matter with this plugin. It would help us PMC members to understand the reasons why you rely on the plugin (too) and especially the reasons why you can't migrate to the proposed XHR/fetch alternative.

https://lists.apache.org/thread.html/r4f85264a457ca57301cea226310f920b7f08e5657924a89899ab2b58%40%3Cdev.cordova.apache.org%3E

**Comment by HarelM** [comment] 2020-07-26 13:08
@timbru31 I have the same issue as @alssl-ross describes.
I have a few lerge files that I need to download from my server nd save to the file system - total size of the files is 500Mb. Each file is between 100Mb and 300Mb. I can't split those files into smaller files because they are sqlite database files and splitting them would be a headache.
When I download them using angular/ionic http client the file is loaded into memory before I can store it in the file system using the file-plugin.
In some cases, specifically on iOS, this causes a "white screen of death".
Somewhat related to this issue (see my comment at the end) 
https://github.com/apache/cordova-plugin-file/issues/364
When all I want to do is download a file and store it somewhere in the application folders there's a problem in iOS and sometimes it fails when not using this plugin.
I think the problem is related to how much memory is used by the webview, not sure though...

**Comment by timbru31** [comment] 2020-07-26 14:37
@HarelM could you please share this insight with the dev mailing list as requested? I'm pretty sure not all active PMC members and committers are watching this issue.

**Comment by DominicGBauer** [comment] 2020-08-19 03:43
@timbru31 I can't seem to reply to the mailing list but looking at the solution proposed by cordova of using window.requestFileSystem doesn't seem to be a viable solution anymore. 

Considering what MDN docs say about it https://developer.mozilla.org/en-US/docs/Web/API/Window/requestFileSystem.

"Even compared to the rest of the File and Directory Entries API, requestFileSystem() is especially non-standard; only Chrome implements it, and all other browser makers have decided that they will not implement it. It has even been removed from the proposed specification. Do not use this method!"

It also doesn't seem to be in TypeScript typings.

**Comment by HarelM** [comment] 2020-08-19 06:07
I'm pretty sure I already added my comments to that thread, but I don't see it there for some reason. I sent another mail, I hope it will be added...

**Closed** 2020-08-25 21:44 UTC

**Comment by sandip7878** [comment] 2020-10-03 12:19
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

It's working for me. Thank you

**Comment by imdox** [comment] 2020-12-08 05:50
> > By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> > ```
> >     NSString* userAgent = [self.commandDelegate userAgent];
> >     if (userAgent) {
> >         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
> >     }
> > ```
> 
> It's working for me.
> Thank you for saving my time

its not working.... when i comment this lines, create following issue
<img width="1027" alt="Screenshot 2020-12-08 at 11 19 15 AM" src="https://user-images.githubusercontent.com/43648716/101445320-4c453f80-3947-11eb-976e-9d849bc6afcd.png">

**Comment by imdox** [comment] 2020-12-08 05:52
> Same error with:
> cordova-ios: 6.0.0
> cordova-plugin-file-transfer : 1.7.1
> 
> I cant not compile with @jansc Solution because Ive got: Plugins/cordova-plugin-inappbrowser/CDVWKInAppBrowser.m:27:9: 'Cordova/CDVUserAgentUtil.h' file not found if I delete Lines 107-110

facing same issue.

**Comment by XtreZz** [comment] 2020-12-11 11:02
will this be released soon ? i want to know if i should have another approach on this or wait for the release. Thanks

**Comment by rolinger** [comment] 2020-12-12 14:44
@kolbasa 

> Thank you very much, I'll try that. You can no longer publish an app with cordova-ios v5.1.1.
> ~This issue should be a top priority.~
> I have only just read that the plugin is deprecated :D.

This is not true.  I am using Xcode 12, and my Ionic v1 app is using `cordova-ios @5.1.1`, everything compiles just fine and is accepted by Apple.  What Apple will no longer accept are apps still using `UIWebView` - everyone must convert to `WKWebView`

**Comment by timbru31** [comment] 2020-12-12 14:47
Please note, that the deadline for updating UIWebView based apps has been extended by an unknown time: https://developer.apple.com/news/?id=edwud51q

**Comment by rolinger** [comment] 2020-12-12 14:52
@timbru31 - technically true, but for apps that are already on the store front.  New apps are required to use WKWebView.  I have two apps, one still on UIWebView that is currently being accepted, and a new app (that is a splintered service from the first app) that had to be submitted with WKWebView.  Any chance you could take a look at the bug I submitted last night, related to `result.lengthComputable` in success callback?

**Comment by serverbroad** [comment] 2021-01-22 17:59
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

work for me

**Comment by trackmyapp** [comment] 2021-01-26 12:48
@vtellez and @imdox
Did you find any alternative solution or workaround to compile the code? Or is the transition off of this plugin to https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html the only solution?

**Comment by trackmyapp** [comment] 2021-02-09 14:36
> > By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> > ```
> >     NSString* userAgent = [self.commandDelegate userAgent];
> >     if (userAgent) {
> >         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
> >     }
> > ```
> 
> work for me

worked for me too but had to update the plugin "cordova-plugin-ionic-webview". So don't forget to update your other plugins.

**Comment by markdegrootnl** [comment] 2021-02-19 22:11
Can this fix be released please?

**Comment by regnete** [comment] 2021-03-08 11:37
Downloading many or large files via XHR is very slow in cordova even if we use chunked downloads (Range-Header). Looks like passing the byte array from javascript to the native backend is the bottleneck. The app hangs while transfering the chunks to the native. So using XHR is not an option for us na d we switched back to this plugin.
When will this fix be released?

**Comment by msudol** [comment] 2021-03-18 01:57
too bad someone can't just develop a plugin that lets us use the same methods as cordova-file-transfer, with the XHR method, I believe that would be called a shim, or wrapper plugin, or post a more idiot dev friendly transition article..   my code base relies heavily on something that looks like this: 

    var ft = new FileTransfer();
    ft.upload(imageURI, app.image_upload, win, fail, options);

If I could just load something using the XHR method that would let me create a filetransfer call that would be spectacular

**Comment by rolinger** [comment] 2021-03-18 14:53
@msudol - why don't you contribute to the project versus criticizing it.  I am certain everyone would appreciate the effort.

**Comment by msudol** [comment] 2021-03-18 15:31
>  
> @msudol - why don't you contribute to the project versus criticizing it. I am certain everyone would appreciate the effort.

I made no criticism, only a request. Your comment is cringy, unwarranted, and provides even less contribution than mine. Where is your PR speaking of contributing.

**Comment by rolinger** [comment] 2021-03-18 15:38
@msudol - `too bad someone can't just develop a plugin that lets us use the same methods as cordova-file-transfer` 

Doesn't sound like a request....reads like a whiny complaint.  Just sayin'.  Moving along now...

**Comment by timbru31** [comment] 2021-03-18 16:17
Please be civil :)

I'll remove any other off-topic comments after this one without a warning. Thanks!

**Comment by mirko77** [comment] 2021-03-25 18:48
Quick question, on cordova-ios 6.2.0 which by default uses WKWebView, is it only a matter of commenting out those 4 lines of code? 

```
NSString* userAgent = [self.commandDelegate userAgent];
    if (userAgent) {
        [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
    }
```

**Comment by regnete** [comment] 2021-03-26 07:19
@mirko77 I'm using this fork. Works for me. https://github.com/sitewaerts/cordova-plugin-file-transfer.
Diff: https://github.com/apache/cordova-plugin-file-transfer/compare/master...sitewaerts:master

I created that fork to merge the fixes from https://github.com/zoopit/cordova-plugin-file-transfer plus the current comits of https://github.com/apache/cordova-plugin-file-transfer

**Comment by mirko77** [comment] 2021-03-26 08:42
> @mirko77 I'm using this fork. Works for me. https://github.com/sitewaerts/cordova-plugin-file-transfer.
> Diff: [master...sitewaerts:master](https://github.com/apache/cordova-plugin-file-transfer/compare/master...sitewaerts:master)
> 
> I created that fork to merge the fixes from https://github.com/zoopit/cordova-plugin-file-transfer plus the current commits of https://github.com/apache/cordova-plugin-file-transfer

Thanks, very useful, I will give it a try

**Comment by markdegrootnl** [comment] 2021-03-26 09:23
I'm using https://github.com/dpa99c/cordova-plugin-file-transfer for now

**Comment by regnete** [comment] 2021-03-26 10:13
> I'm using https://github.com/dpa99c/cordova-plugin-file-transfer for now

But thats 12 commits behind apache:master.

**Comment by Noext** [comment] 2021-05-07 14:34
still not working on cordova 10

**Comment by mirko77** [comment] 2021-05-07 14:48
@Noext I do not think this repository ever will, try the linked forks

**Comment by aacassandra** [comment] 2021-05-23 08:06
> [hub.com/dpa99c/cordova-plugin-file-transfer](https://github.com/dpa99c/cordova-plugin-file-transfer)

thankyou, its works with capacitor 3 and last ionic/vue 2021

**Comment by FranGhe** [comment] 2021-05-27 10:36
Just a question (I have loose some comments) but these plugins
https://github.com/dpa99c/cordova-plugin-file-transfer 
https://github.com/sitewaerts/cordova-plugin-file-transfer
work for cordova 10?

**Comment by sanderschnydrig** [comment] 2021-07-14 11:59
To anyone facing this issue this is the only one that worked for me:

(add this to dependencies)

```json
"cordova-plugin-file-transfer": "https://github.com/dpa99c/cordova-plugin-file-transfer/tarball/446b175154491f67bc04a657041a26bc5db92b30",
```

**Comment by regnete** [comment] 2021-07-14 12:09
> Just a question (I have loose some comments) but these plugins
> https://github.com/dpa99c/cordova-plugin-file-transfer
> https://github.com/sitewaerts/cordova-plugin-file-transfer
> work for cordova 10?
> 
> Excuse my ignorance, but if they work... why to install them the command is always the same?
> cordova plugin add cordova-plugin-file-transfer
> 
> I have to do something else?

cordova plugin add https://github.com/sitewaerts/cordova-plugin-file-transfer

**Comment by rhafiko** [comment] 2021-07-30 19:53
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

it worked for me. Thanks.

**Comment by muuvmuuv** [comment] 2021-08-16 08:05
This is again not working. Only the fork worked for me.

**Comment by ng22792** [comment] 2021-08-23 06:04
> This is again not working. Only the fork worked for me.

+1

**Comment by thesurya9** [comment] 2021-11-01 13:26
> By removing lines 107-110 from CDVFileTransfer.m I was able to compile:
> 
> ```
>     NSString* userAgent = [self.commandDelegate userAgent];
>     if (userAgent) {
>         [req setValue:userAgent forHTTPHeaderField:@"User-Agent"];
>     }
> ```

you are life saver bro.

**Comment by sushibear** [comment] 2021-11-17 16:03
> > Excuse my ignorance, but if they work... why to install them the command is always the same?
> > cordova plugin add cordova-plugin-file-transfer
> > I have to do something else?
> 
> cordova plugin add https://github.com/sitewaerts/cordova-plugin-file-transfer

Thanks for the fork, seems to work nicely! :)

**Comment by byronigoe** [comment] 2021-12-18 02:11
> https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

Anyone else notice that the download example in this blog post doesn't actually save the file? You can use cordova-plugin-file to do that like the example here: https://github.com/apache/cordova-plugin-file#write-to-a-file-

**Comment by kingkarki** [comment] 2022-02-21 08:48
> Given the plugin is deprecated, is it worth creating a pull request? I'm not sure if anyone is able to merge the pull request if it was created.
> 
> I've forked this repository and made this change in if it's of use to anyone:
> 
> https://github.com/alssl-ross/cordova-plugin-file-transfer

Thank you very much

**Comment by danielehrhardt** [comment] 2022-05-06 21:45
`npm install https://github.com/apache/cordova-plugin-file-transfer.git`

**Comment by vesper8** [comment] 2023-03-11 15:47
To anyone confused (like I was) by the above... it seems that running

`cordova plugin add cordova-plugin-file-transfer` installs the latest tagged release from 2018

And running `cordova plugin add https://github.com/apache/cordova-plugin-file-transfer` installs the master version which includes the fix

I guess tagging a new release would be pretty great

**Comment by HarelM** [comment] 2023-03-11 16:18
I tried to push that forward but failed, there are falling tests that prevent publishing a new version of this package to npm.
If anyone is up for it, it would be great...

**Comment by rpcarnell** [comment] 2023-05-09 06:45
I tried jansc 's solution, but when I type ionic capacitor run ios -l --external, the file goes back to what it was. Changes are reverted. Any idea of why this happens?

**Comment by danicholls** [comment] 2024-06-03 06:05
NPM seems to have the current version (2.0.0) now. (From 09/2023.)

I don't know if there's any reason to keep using the sitewaerts version (which was a lifesaver!) or anything.
