### ISSUE TITLE
Missing any permission information within this plugin's documentation?

### ISSUE THREAD

**Issue by qroft** [apache/cordova-plugin-file-transfer#243] opened 2019-09-25 09:14 UTC
# Bug Report
I created an app that works like a charm on two of my phones and one tablet.
The app downloads a ZIP file from my server to cordova.file.externalDataDirectory.
One some users though, the download does not even start.

## Problem
On some user's phone, the download does not even start

### What is expected to happen?
Download a ZIP from http://www.myserver.com/thezip.zip to the external app's data folder.

### What does actually happen?
On my devices everything is fine.
On a friend's Huawei phone, the download does not even start and i get no error info.
I thought that this is due to any needed app permissions, but he checked that the app has
a storage permission.
**It would be awesome if there could be any information or an example within the documentation about the necessary lines of permissions needed in config.xml** 

## Information
Made with latest Phonegap.
App is available in Play store (Remember the .GIF)

### Command or Code
Via Cordova Run Android.

### Environment, Platform, Device
Works under a Samsung, BQ and Lenovo device.
Does NOT work with a Huawei device (and so, probably others too)

### Version information
cordova-plugin-android-permission 1.0.0
cordova-plugin-file 6.0.2
cordova-plugin-file-transfer 1.7.1
cordova-plugin-whitelist 1.3.4.
cordova-plugin-zip 3.1.0
cordova-plugin-contentsync 1.4.2

## Checklist
- [X] I searched for existing GitHub issues
- [X] I updated all Cordova tooling to most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment] 2020-09-15 20:44
Duplicate of https://github.com/apache/cordova-plugin-file-transfer/issues/239

**Closed by breautek** 2020-09-15 20:44 UTC

**Comment by ugale-deepak3010** [comment] 2021-05-05 14:52
always use onreadydevice to manage permission sometime happen with me very wrongly but I understood
